const path = require('node:path');

const PROJECT_ROOT = path.resolve(__dirname, '..', '..', '..');
const TRANSCRIPTS_DIR = path.join(PROJECT_ROOT, 'transcripts');
const ENV_FILE_PATH = path.join(PROJECT_ROOT, '.env');

const DEFAULT_MIME_TYPE = 'audio/webm';
const DEFAULT_SOURCE_MODEL = 'gpt-4o-transcribe-diarize';
const DEFAULT_PARTICIPANT_COUNT = 1;
const MAX_MEETING_TITLE_LENGTH = 160;
const MEETING_SUMMARY_MAX_WORDS = 18;
const MEETING_SUMMARY_INPUT_MAX_CHARS = 5000;
const MEETING_SUMMARY_ERROR_MAX_CHARS = 120;
const SUMMARY_ERROR_RETRY_INTERVAL_MS = 15 * 60 * 1000;
const SUMMARY_SOURCE_AZURE_OPENAI = 'azure-openai';
const SUMMARY_SOURCE_ERROR = 'summary-error';

module.exports = {
  DEFAULT_MIME_TYPE,
  DEFAULT_PARTICIPANT_COUNT,
  DEFAULT_SOURCE_MODEL,
  ENV_FILE_PATH,
  MEETING_SUMMARY_ERROR_MAX_CHARS,
  MEETING_SUMMARY_INPUT_MAX_CHARS,
  MEETING_SUMMARY_MAX_WORDS,
  MAX_MEETING_TITLE_LENGTH,
  PROJECT_ROOT,
  SUMMARY_ERROR_RETRY_INTERVAL_MS,
  SUMMARY_SOURCE_AZURE_OPENAI,
  SUMMARY_SOURCE_ERROR,
  TRANSCRIPTS_DIR,
};
